###### rsync server
  extremeshok-rsyncd:
    image: extremeshok/rsyncd:latest
    environment:
      - USERNAME=myuser
      - PASSWORD=a_secure_password
    volumes:
      - ./data/:/data/:rw
    restart: always
    ports:
      - "873:873"
